export const S = {
shapeMode: '2d',
mmLabelGroup: null,
mmState: 'off',
rotationLocked: false,
nextLayerId: 1,
activeLayerId: null,
activeShapeId: null,
crosshairActive: false,
activeModule: 'tools',
h3Open: false,
lastPlaced: null,
crumbs: ['Drawing Tools'],
crumbBack: null,
h2BackAttached: false,
pendingP2P: null,
selectedAxis: 'X',
manipulationActive: false,
manipulationCleanup: null,
toastTimer: null,
};